[tox]
envlist = py{39,310,311,312,313,314}, backend-{pandas,polars}
isolated_build = true

[testenv]
runner = uv-venv-runner
extras = dev
package = editable
commands = pytest --skip-cli {posargs}

[testenv:backend-{pandas,polars}]
runner = uv-venv-runner
extras =
    pandas: pandas
    polars: polars
deps = pytest
package = editable
commands =
    pandas: pytest --skip-cli --ignore=test/test_narwhals.py {posargs}
    polars: pytest --skip-cli {posargs}
